spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/houhan_library
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
